apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-clone-config
  labels:
    app.kubernetes.io/name: registry-clone
data:
  REDIS_URL: redis://registry-clone-redis:6379/0
  RUN_ID: default

  STREAM_TAGS: stream:tags
  STREAM_BLOBS: stream:blobs
  STREAM_BLOB_EVENTS: stream:blob-events
  STREAM_PUBLISH: stream:publish
  STREAM_MANIFEST_EVENTS: stream:manifest-events

  GROUP_METADATA: cg:metadata
  GROUP_BLOB: cg:blob-workers
  GROUP_PUBLISH: cg:publish-workers

  SOURCE_AUTH_FILE: /auth/source-auth.json
  TARGET_AUTH_FILE: /auth/target-auth.json

  METADATA_CONCURRENCY: "4"
  BLOB_LOCAL_CONCURRENCY: "32"
  PUBLISH_CONCURRENCY: "4"

  METRICS_ADDR: 0.0.0.0:9090
  METRICS_PATH: /metrics

  SOURCE_TLS_VERIFY: "true"
  TARGET_TLS_VERIFY: "true"
  COPY_BLOB_BINARY: /usr/local/bin/skopeo
