apiVersion: v1
kind: Secret
metadata:
  name: registry-clone-auth
  labels:
    app.kubernetes.io/name: registry-clone
type: Opaque
stringData:
  source-auth.json: |
    {
      "auths": {
        "source.registry.example.com": {
          "auth": "BASE64_USERNAME_COLON_PASSWORD"
        }
      }
    }
  target-auth.json: |
    {
      "auths": {
        "target.registry.example.com": {
          "auth": "BASE64_USERNAME_COLON_PASSWORD"
        }
      }
    }
